- name: Upgrade dnf
  dnf:
  when: package_upgrade == "yes"
  become: true
  become_user: root
  become_method: sudo
- name: Install dnf packages
  dnf:
    name: '{{ item }}'
    update_cache: true
  become: true
  become_user: root
  become_method: sudo
  loop: '{{ packages }}'
- name: Remove dnf packages
  dnf:
    name: '{{ item }}'
    update_cache: true
    state: absent
  become: true
  become_user: root
  become_method: sudo
  loop: '{{ remove_packages }}'
