- name: Check if .emacs configuration exists
  stat: path="{{dotfiles_user_home}}/.emacs"
  register: emacsconfig_stat
  become: false
- name: Back up .emacs configuration
  command: mv ~/.emacs ~/.emacs.bak.{{ ansible_date_time.iso8601 }}
  when: emacsconfig_stat.stat.exists
  become: false
- name: Copy .emacs to home folder
  file:
    src: '{{ dotfiles_home }}/roles/emacs/files/emacs'
    dest: '{{ dotfiles_user_home }}/.emacs'
    owner: '{{ user }}'
    state: hard
  become: false
- name: create a symbolic link of a directory
  file:
    src: '{{ dotfiles_home }}/roles/emacs/files/emacs.d/snippets'
    dest: '{{ dotfiles_user_home }}/.emacs.d/snippets'
    owner: '{{ user }}'
    state: link
  become: false
